=== api-evangelist/cisco-voice-portal/json-schema/cisco-voice-portal-call-control-sip-session-detail-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "SipSessionDetail",
  "type": "object",
  "properties": {
    "sessionId": {
      "type": "string"
    },
    "callId": {
      "type": "string"
    },
    "callGuid": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "fromUri": {
      "type": "string"
    },
    "toUri": {
      "type": "string"
    },
    "fromTag": {
      "type": "string"
    },
    "toTag": {
      "type": "string"
    },
    "cseq": {
      "type": "integer"
    },
    "transport": {
      "type": "string"
    },
    "localAddress": {
      "type": "string"
    },
    "remoteAddress": {
      "type": "string"
    },
    "startTime": {
      "type": "string"
    },
    "lastActivityTime": {
      "type": "string"
    }
  }
}

=== api-evangelist/cisco-voice-portal/examples/cisco-voice-portal-call-control-sip-session-detail-example.json
{
  "sessionId": "500123",
  "callId": "500123",
  "callGuid": "500123",
  "state": "example_value",
  "fromUri": "example_value",
  "toUri": "example_value",
  "fromTag": "example_value",
  "toTag": "example_value",
  "cseq": 10,
  "transport": "example_value",
  "localAddress": "example_value",
  "remoteAddress": "example_value",
  "startTime": "example_value",
  "lastActivityTime": "example_value"
}
